# Site settings
title: Nathan E Myers
email: nathanemyers@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a full stack developer based in Chicago, IL
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nathanemyers.com" # the base hostname & protocol for your site
twitter_username: nathanemyers
github_username:  nathanemyers

# Build settings
markdown: kramdown
